# Generated by Django 4.0 on 2021-12-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0004_alter_fruit_timestamp_alter_fruit_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='author',
            new_name='owner',
        ),
    ]
